sudo: required
dist: trusty

language: php

php:
  - '7.2'

services:
  - mysql

env:
  global:
    - APP_ENV=test
    - USER="Travis CI"
    - EMAIL="travis@travis-ci.org"
    - GITHUB_REPO="github.com/${TRAVIS_REPO_SLUG}.git"
  matrix:
    - NODE_VERSION=8

addons:
  sonarcloud:
    organization: "sproogen-github"

cache:
  directories:
    - $HOME/.composer/cache/file
    - vendor
    - app/node_modules

branches:
  only:
    - master
    - develop

before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $NODE_VERSION && nvm install-latest-npm
  - ./scripts/bump-version.sh

install:
  - composer install
  - (cd app && npm ci)

before_script:
  - php bin/console about
  - php bin/console doctrine:database:create
  - composer compile

script:
  - vendor/bin/phpcs --standard=PSR2 --ignore=Migrations src/
  - vendor/bin/phplint src
  - SYMFONY_DEPRECATIONS_HELPER=disabled vendor/bin/simple-phpunit
  - SYMFONY_DEPRECATIONS_HELPER=disabled vendor/bin/codecept run
  - (cd app && npm run lint)
  - (cd app && npm run test -- --coverage --ci)
  - ./scripts/update-sonar-version.sh && sonar-scanner

after_success:
  - ./scripts/merge-downstream.sh
